# This is a basic workflow to help you get started with Actions
name: Do Good Get Good unit tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - "*"
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: |
        cd src
        npm install
    - run: |
        cd src
        npm test
      # You may pin to the exact commit or the version.
      # uses: RedaktionsNetzwerk-Deutschland/action-jest-reporter@6e23f271b4fb10248a260e72fe6d1bcddeea9f4a
    - uses: RedaktionsNetzwerk-Deutschland/action-jest-reporter@v1.0.0
      if: always()
      #with:
        # The GitHub Token. This is only used, if none is provided via Env.
        # GITHUB_TOKEN: # optional
        # Glob for matching the Jest Output files
        #json-glob: "**/jest-output.json"
        # Specify a custom workdirectory if needed. By default env.GITHUB_WORKSPACE is used.
        #workdir: ${env.GITHUB_WORKSPACE}/src
