# This is a basic workflow to help you get started with Actions
name: Build Android Debug App
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_android:
    name: Building android apk
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: "9.0.4" # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
        working-directory: src/
      - name: Build Android apk (debug)
        run: ./gradlew assembleDebug
        working-directory: src/android
      - uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: "**/*.apk"
