name: Build Android APK
on: 
  workflow_dispatch:
  
jobs: 
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Set Secret Properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: echo "$LOCAL_PROPERTIES" > src/android/app/local.properties
    
      - name: Prepare release keystore
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > dggg_key.keystore.asc
          gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch dggg_key.keystore.asc > src/android/app/dggg_key.keystore
      
      - name: Install dependencies
        run: cd src/ && npm install
      
      - name: Build Android APK
        run: cd src/ && cd android && ./gradlew assembleRelease
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          working-directory: src/
          name: release
          path: android/app/build/outputs/apk/release/app-release.apk
